Item + Movie class
Foxxite/HR-Bioscoop-Project-B pull request #5
Opened 2021-03-20 13:59 UTC by Chakir010

Ik heb de item en de movie class gemaakt

2021-03-20 14:00 UTC, Foxxite requested changes
Classes en methods hebben geen doucmentatie.

2021-03-20 14:00 UTC, Foxxite commented on Cinema App/Cinema App/Item.cs
> +        public abstract bool IsAvailable();
Geen Documentatie

2021-03-22 09:30 UTC, Foxxite approved these changes

2021-03-22 09:31 UTC, yannickdv01 approved these changes

2021-03-22 09:32 UTC, merged